export const AVATARS = [
  { slug: 'ronaldo',       name: 'Ronaldo' },
  { slug: 'zidane',        name: 'Zidane' },
  { slug: 'ronaldinho',    name: 'Ronaldinho' },
  { slug: 'beckham',       name: 'Beckham' },
  { slug: 'henry',         name: 'Henry' },
  { slug: 'figo',          name: 'Figo' },
  { slug: 'rivaldo',       name: 'Rivaldo' },
  { slug: 'bergkamp',      name: 'Bergkamp' },
  { slug: 'shearer',       name: 'Shearer' },
  { slug: 'delpiero',      name: 'Del Piero' },
  { slug: 'totti',         name: 'Totti' },
  { slug: 'raul',          name: 'Raul' },
  { slug: 'kluivert',      name: 'Kluivert' },
  { slug: 'batistuta',     name: 'Batistuta' },
  { slug: 'maldini',       name: 'Maldini' },
  { slug: 'robertocarlos', name: 'R. Carlos' },
  { slug: 'cafu',          name: 'Cafu' },
  { slug: 'seedorf',       name: 'Seedorf' },
  { slug: 'cannavaro',     name: 'Cannavaro' },
  { slug: 'inzaghi',       name: 'Inzaghi' },
]
